apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole-pods
  namespace: dns-pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
      - name: pihole
        image: pihole/pihole:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-service
  namespace: dns-pihole
spec:
  clusterIP: 10.96.212.110
  clusterIPs:
    - 10.96.212.110
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
      name: pihole
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
