apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-kubeadmin
  namespace: dev-internal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-kubeadmin
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dev-kubeadmin
    spec:
      containers:
        - name: dev-kubeadmin
          image: ubuntu:xenial
          ports:
            - containerPort: 2269
          command:
            - /bin/sh
            - '-c'
            - tail -f /dev/null
			- ["printenv"]
		  args: ["HOSTNAME", "KUBERNETES_PORT"]
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30